name          'hadenlabs-firefox'
version       '1.0.1'
source        ''
author        '@slovacus'
license       'Mit'
summary       ''
description   ''
project_page  'https://github.com/hadenlabs/puppet-module-firefox'

dependency 'puppetlabs/stdlib'
